[package]
authors = ["Sturdy <sturdy@apollo.farm>"]
edition = "2021"
name = "base-vault"
version = "0.1.0"

[dependencies]
cosmwasm-std = { version = "1.2.1" }
cw-storage-plus = "1.0.1"
serde = {version = "1.0.152", default-features = false, features = ["derive"]}
apollo-cw-asset = "0.1.0"
cw-vault-token = "0.1.0"
